/*
 * SECD VM startup for ESP32-S3.
 * Loads bytecode merged into the app image (secd_bytecode.cpp generated by
 * the Makefile) and runs it.
 *
 * Two firmware variants, selected at build time via SECD_DEBUG_BUILD:
 *  - debug   (default): boots its own USB console so the startup banner is
 *                        always printed, then tears USB down and lets the Lisp
 *                        program re-initialize it (%usb-init/%usb-start).
 *  - release          : starts bytecode immediately, no serial output, no waits.
 */
#include "secd/machine.h"
#include "secd/heap.h"
#include "hal/hal.h"
#include "usb.h"
#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#ifndef HEAP_OBJECTS
#define HEAP_OBJECTS 8192
#endif

#ifndef SECD_MACHINE_VERSION
#define SECD_MACHINE_VERSION "0.0.1.0"
#endif

#ifndef SECD_DEBUG_BUILD
#define SECD_DEBUG_BUILD 1
#endif

#ifndef SECD_FEATURE_HID
#define SECD_FEATURE_HID 0
#endif

extern "C" const uint8_t secd_bytecode[];
extern "C" const uint32_t secd_bytecode_len;

static secd_heap_t heap;
static secd_machine_t machine;

#if SECD_DEBUG_BUILD && SECD_FEATURE_HID
/* Debug boots its own USB console, prints startup info, then tears it down so
 * the Lisp program can re-initialize USB (%usb-init/%usb-start) with the full
 * factory. This guarantees the boot banner is seen even if Lisp never starts
 * USB. */
static void secd_info(const char *fmt, ...) {
    char buf[192];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    secd_console_write((const uint8_t *)buf, strlen(buf));
}
#define SECD_INFO(...) secd_info(__VA_ARGS__)
#define SECD_WAIT_MS(ms) hal_delay(ms)
#else
#define SECD_INFO(...) printf(__VA_ARGS__)
#define SECD_WAIT_MS(ms) hal_delay(ms)
#endif

extern "C" int secd_start(void) {
    hal_init();

#if SECD_DEBUG_BUILD && SECD_FEATURE_HID
    secd_usb_init();
    secd_usb_start();
    secd_console_write((const uint8_t *)"Waiting for host console...\n", 29);
    while (!secd_console_ready()) {
        hal_delay(20);
    }

    SECD_INFO("SECD Machine v%s\n", SECD_MACHINE_VERSION);
    SECD_INFO("Platform: ESP32-S3\n");
    SECD_INFO("Features: %s\n", SECD_FEATURES_STR);
#endif

    if (secd_heap_init(&heap, HEAP_OBJECTS) != 0) {
        SECD_INFO("Heap init failed\n");
        return 1;
    }
    if (secd_machine_init(&machine, &heap) != 0) {
        SECD_INFO("Machine init failed\n");
        return 1;
    }

    /* Bytecode is merged into the app image as code+const (no "SECD" header). */
    SECD_INFO("Bytecode: %u bytes\n", (unsigned)secd_bytecode_len);

#if SECD_DEBUG_BUILD && SECD_FEATURE_HID
    SECD_INFO("Deinitializing boot console, Lisp takes over USB.\n");
    secd_usb_deinit();
#endif

    secd_execute(&machine, secd_bytecode, secd_bytecode_len);
    SECD_INFO("Done: steps=%u error=%u\n", (unsigned)machine.steps, (unsigned)machine.error);

    for (;;) {
        hal_delay(1000);
    }
}