/*
 * SECD VM startup for ESP32-S3.
 * Loads bytecode merged into the app image (secd_bytecode.cpp generated by
 * the Makefile) and runs it.
 */
#include "secd/machine.h"
#include "secd/heap.h"
#include "hal/hal.h"
#include <stdio.h>

#ifndef HEAP_OBJECTS
#define HEAP_OBJECTS 8192
#endif

#ifndef SECD_MACHINE_VERSION
#define SECD_MACHINE_VERSION "0.0.1.0"
#endif

#ifndef SECD_DEBUG_BUILD
#define SECD_DEBUG_BUILD 1
#endif

#if SECD_DEBUG_BUILD
#define SECD_INFO(...) printf(__VA_ARGS__)
#else
#define SECD_INFO(...) ((void)0)
#endif

extern "C" const uint8_t secd_bytecode[];
extern "C" const uint32_t secd_bytecode_len;

static secd_heap_t heap;
static secd_machine_t machine;

extern "C" int secd_start(void) {
    hal_init();

    SECD_INFO("SECD Machine v%s\n", SECD_MACHINE_VERSION);
    SECD_INFO("Platform: ESP32-S3\n");

    if (secd_heap_init(&heap, HEAP_OBJECTS) != 0) {
        SECD_INFO("Heap init failed\n");
        return 1;
    }
    if (secd_machine_init(&machine, &heap) != 0) {
        SECD_INFO("Machine init failed\n");
        return 1;
    }

    /* Bytecode is merged into the app image as code+const (no "SECD" header). */
    SECD_INFO("Bytecode: %u bytes\n", (unsigned)secd_bytecode_len);

    secd_execute(&machine, secd_bytecode, secd_bytecode_len);
    SECD_INFO("Done: steps=%u error=%u\n", (unsigned)machine.steps, (unsigned)machine.error);

    for (;;) {
        hal_delay(1000);
    }
}