/*
 * Generated by the Makefile: embeds compiled SECD bytecode into the app image.
 * This placeholder is replaced by `make esp32c3-blink` (or the ESP32C3-MERGE
 * rule) with the real compiled program.
 */
#include <stdint.h>
extern "C" const uint8_t secd_bytecode[] = { 0x53,0x45,0x43,0x44 };
extern "C" const uint32_t secd_bytecode_len = 4;